// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using airbnb_clone_BE.Data;

#nullable disable

namespace airbnb_clone_BE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240307085449_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("airbnb_clone_BE.Data.Entity.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AmentityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmentityName = "Wifi",
                            Icon = "iconoir:wifi"
                        },
                        new
                        {
                            Id = 2,
                            AmentityName = "TV",
                            Icon = "gala:tv"
                        },
                        new
                        {
                            Id = 3,
                            AmentityName = "Bếp",
                            Icon = "mdi:stove"
                        },
                        new
                        {
                            Id = 4,
                            AmentityName = "Máy giặt",
                            Icon = "icon-park-outline:washing-machine"
                        },
                        new
                        {
                            Id = 5,
                            AmentityName = "Chỗ đỗ xe miễn phí tại nơi ở",
                            Icon = "fluent:vehicle-car-16-regular"
                        },
                        new
                        {
                            Id = 6,
                            AmentityName = "Chỗ đỗ xe có thu phí trong khuôn viên",
                            Icon = "fluent:vehicle-car-parking-32-regular"
                        },
                        new
                        {
                            Id = 7,
                            AmentityName = "Điều hòa nhiệt độ",
                            Icon = "material-symbols:mode-cool"
                        },
                        new
                        {
                            Id = 8,
                            AmentityName = "Không gian làm việc riêng",
                            Icon = "lucide:lamp-desk"
                        });
                });

            modelBuilder.Entity("airbnb_clone_BE.Data.Entity.Palace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Palaces");
                });

            modelBuilder.Entity("airbnb_clone_BE.Data.Entity.PalaceAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.Property<int>("PalaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PalaceAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
